data:
  file_path: 'data/100k_Prim.npy'

dataset:
  # Splits are ~ 60% training, 20% validation, 20% test
  class: MazeDataset
  name: Prim
  transforms:
    sequential: [ToTensor, Unsqueeze]

  train_params:
    idx_range: [0, 6000]

  validation_params:
    idx_range: [6000, 8000]

  test_params:
    idx_range: [8000, 10000]