data:
  file_path: 'data/10k_Prim.npy'

dataset:
  # Splits are ~ 60% training, 20% validation, 20% test
  class: MazeDataset
  name: Prim
  transforms:
    sequential: [ToTensor, Unsqueeze]

  train_params:
    idx_range: [0, 6000]

  validation_params:
    idx_range: [6000, 8000]

  test_params:
    idx_range: [8000, 10000]

model:
  class: VAE
  encoder_class: TransformerEncoder
  decoder_class: TransformerDecoder
  is_conditional: True
  name: TransformerVAE
  prior_class: MogPrior
  prior_params:
    latent_dim: 2048
    num_components: 16
  encoder_params:
    input_dim: [1,65,65]
    out_channels: [256, 128, 64]
    layers_per_block: 2
    kernel_size: 3
    down_sample_factor: 2
    num_heads: 16
  decoder_params:
    input_shape: [64, 8, 8]
    output_shapes: [[256, 16, 16],[128, 32, 32], [32, 65, 65]]
    output_dim: [1, 65, 65]
    conditional_shape: [1,65,65]
    layers_per_block: 1
    kernel_size: 3

training:
  model_name: fractal/TransformerVAE.pt
  batch_size: 32
  num_epochs: 250
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
  annealer_params:
    annealing_type: cosine
    beta_0: 0.0
    cyclical: False
    disable: False