data:
  file_path: 'data/10k_DFS.npy'

dataset:
  # Splits are ~ 60% training, 20% validation, 20% test
  class: MazeDataset
  name: DFS
  transforms:
    sequential: [ToTensor, Flatten]

  train_params:
    idx_range: [0, 6000]

  validation_params:
    idx_range: [6000, 8000]

  test_params:
    idx_range: [8000, 10000]

model:
  class: VAE
  encoder_class: FcEncoder
  decoder_class: FcDecoder
  is_conditional: True
  name: FcVAE
  prior_class: MogPrior
  prior_params:
    latent_dim: 64
    num_components: 16
  encoder_params:
    input_dim: 4225
    hidden_dims: [512, 256, 128]
    latent_dim: 64
  decoder_params:
    latent_dim: 64
    hidden_dims: [128, 256, 512]
    output_dim: 4225

training:
  model_name: dfs/FcVAE.pt
  batch_size: 32
  num_epochs: 250
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
  annealer_params:
    annealing_type: cosine
    beta_0: 0.0
    cyclical: False
    disable: False
