data:
  file_path: 'data/10k_dataset.npy'

dataset:
  # Splits are ~ 60% training, 20% validation, 20% test
  class: MazeDataset

  transforms:
    sequential: [ToTensor, Flatten]

  train_params:
    idx_range: [0, 6000]

  validation_params:
    idx_range: [6000, 8000]

  test_params:
    idx_range: [8000, 10000]

model:
  class: VAE
  encoder_class: TransformerEncoder
  decoder_class: TransformerDecoder
  is_conditional: True
  prior_class: MogPrior
  prior_params:
    latent_dim: 32
    num_components: 16
  encoder_params:
    input_dim: 15625
    hidden_dims: [256, 128]
    latent_dim: 32
  decoder_params:
    latent_dim: 32
    hidden_dims: [128, 256]
    output_dim: 15625

training:
  model_name: FcVAE.pt
  batch_size: 64
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
