data:
  data_path: 'data/dataset.npy'

dataset:
  # Splits are ~ 60% training, 20% validation, 20% test
  class: MazeDataset

  train_params:
    sample_idx_range: [0, 60000]

  val_params:
    sample_idx_range: [60000, 80000]

  test_params:
    sample_idx_range: [80000, 100000]

model:
  class: VAE
  encoder_class: TransformerEncoder
  decoder_class: TransformerDecoder
  prior_class: MoGPrior
  # TODO: Update when encoder/decoder/prior are implemented
  prior_params:
  
  encoder_params:

  decoder_params:
